# Visit https://github.com/lowlighter/metrics#-documentation for full reference
name: Metrics
on:
  # Schedule updates (each hour)
  schedule: [{cron: "0 * * * *"}]
  # Lines below let you run workflow manually and on each commit
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}

          # Options
          filename: achievements.svg
          user: smir-ant
          template: classic
          base: ""
          config_timezone: Asia/Novosibirsk
          plugin_achievements: yes
          plugin_achievements_display: detailed
          plugin_achievements_ignored: deployer, infographile, forker
          plugin_achievements_secrets: yes
          plugin_achievements_threshold: C
          
  leetcode:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: NOT_NEEDED
          
          # Options
          filename: leetcode.svg
          user: smir-ant
          template: classic
          base: ""
          config_timezone: Asia/Novosibirsk
          plugin_leetcode: yes
          plugin_leetcode_limit_recent: 2
          plugin_leetcode_limit_skills: 10
          plugin_leetcode_sections: solved
          plugin_leetcode_user: smir-ant
